linkPrefix = ""
name = "blockchain_supplychain"
license = "ISC"
version = "1.0.0"
description = "Pharmaceutical SupplyChain using Ethereum Blockchain Network."
homepage = "https://github.com/kamalkishorm/Blockchain_SupplyChain#readme"
author = "Kamal Kishor Mehra"
buildTime = 2019-01-30T17:46:51.802Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "docs"

[interaction]